"""Add Memory and Goals

Revision ID: 5bd2231fbcf9
Revises: ba6271c4964f
Create Date: 2026-07-15 16:53:59.791012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd2231fbcf9'
down_revision: Union[str, None] = 'ba6271c4964f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
