"""Milestone 1 MAS schemas

Revision ID: 6a0d63d68f23
Revises: 5bd2231fbcf9
Create Date: 2026-07-15 18:09:41.093652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a0d63d68f23'
down_revision: Union[str, None] = '5bd2231fbcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_profile')
    op.add_column('episodic_memory', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('episodic_memory', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('episodic_memory', sa.Column('context_snapshot', sa.JSON(), nullable=False))
    op.add_column('episodic_memory', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('episodic_memory', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('episodic_memory_concept_id_fkey', 'episodic_memory', type_='foreignkey')
    op.drop_constraint('episodic_memory_session_id_fkey', 'episodic_memory', type_='foreignkey')
    op.drop_column('episodic_memory', 'session_id')
    op.drop_column('episodic_memory', 'concept_id')
    op.drop_column('episodic_memory', 'created_at')
    op.drop_column('episodic_memory', 'memory_type')
    op.drop_column('episodic_memory', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodic_memory', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('episodic_memory', sa.Column('memory_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('episodic_memory', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('episodic_memory', sa.Column('concept_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('episodic_memory', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('episodic_memory_session_id_fkey', 'episodic_memory', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key('episodic_memory_concept_id_fkey', 'episodic_memory', 'concepts', ['concept_id'], ['id'])
    op.drop_column('episodic_memory', 'timestamp')
    op.drop_column('episodic_memory', 'embedding')
    op.drop_column('episodic_memory', 'context_snapshot')
    op.drop_column('episodic_memory', 'description')
    op.drop_column('episodic_memory', 'event_type')
    op.create_table('learner_profile',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('persona_classification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('curiosity_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('consistency_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('ai_dependency_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('reflection_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('problem_solving_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.Column('weak_topics', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('strong_topics', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('learning_style', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('best_learning_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='learner_profile_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='learner_profile_pkey')
    )
    # ### end Alembic commands ###
