"""Milestone 2 POS Prompt Models

Revision ID: b0199d3b7a58
Revises: 6a0d63d68f23
Create Date: 2026-07-15 18:24:26.695662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0199d3b7a58'
down_revision: Union[str, None] = '6a0d63d68f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
