"""Add DNA fields

Revision ID: ba6271c4964f
Revises: 
Create Date: 2026-07-15 16:39:09.145742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6271c4964f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profile', sa.Column('curiosity_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('confidence_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('consistency_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('ai_dependency_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('reflection_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('communication_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('problem_solving_score', sa.Float(), nullable=False, server_default='0.5'))
    op.add_column('learner_profile', sa.Column('weak_topics', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('learner_profile', sa.Column('strong_topics', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('learner_profile', sa.Column('learning_style', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('learner_profile', sa.Column('best_learning_time', sa.String(), nullable=True))
    op.drop_column('learner_profile', 'dependency_trend_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner_profile', sa.Column('dependency_trend_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('learner_profile', 'best_learning_time')
    op.drop_column('learner_profile', 'learning_style')
    op.drop_column('learner_profile', 'strong_topics')
    op.drop_column('learner_profile', 'weak_topics')
    op.drop_column('learner_profile', 'problem_solving_score')
    op.drop_column('learner_profile', 'communication_score')
    op.drop_column('learner_profile', 'reflection_score')
    op.drop_column('learner_profile', 'ai_dependency_score')
    op.drop_column('learner_profile', 'consistency_score')
    op.drop_column('learner_profile', 'confidence_score')
    op.drop_column('learner_profile', 'curiosity_score')
    # ### end Alembic commands ###
