"""Add EducationalDocumentChunk

Revision ID: bc1e6f42e4b0
Revises: 0653d6e790d7
Create Date: 2026-07-15 18:58:28.531963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1e6f42e4b0'
down_revision: Union[str, None] = '0653d6e790d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_chunks_document_id'), 'educational_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_educational_chunks_topic'), 'educational_chunks', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_educational_chunks_topic'), table_name='educational_chunks')
    op.drop_index(op.f('ix_educational_chunks_document_id'), table_name='educational_chunks')
    op.drop_table('educational_chunks')
    # ### end Alembic commands ###
